apiVersion: v1
kind: Namespace
metadata:
  name: "#{namespace}#"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
  namespace: "#{namespace}#"
data:
  AWS_REGION: "#{location}#"
  AWS_DYNAMODB_TABLE: "#{aws_dynamodb_table}#"

---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
  namespace: "#{namespace}#"
type: Opaque
stringData:
  AWS_SQS_URL: "#{aws_sqs_url}#"