apiVersion: v1
kind: Namespace
metadata:
  name: "#{namespace}#"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-sa
  namespace: "#{namespace}#"
  annotations:
    eks.amazonaws.com/role-arn: "#{aws_evaluation_role_arn}#"
    eks.amazonaws.com/role-arn: "#{aws_analytics_role_arn}#"

---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: "#{namespace}#"
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
  namespace: "#{namespace}#"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      serviceAccountName: analytics-sa
      containers:
        - name: analytics-container
          image: "#{ecr_analytics}#:latest"
          ports:
            - containerPort: 8005
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: analytics-config
                  key: AWS_REGION
            - name: AWS_DYNAMODB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: analytics-config
                  key: AWS_DYNAMODB_TABLE
            - name: AWS_SQS_URL
              valueFrom:
                secretKeyRef:
                  name: analytics-secret
                  key: AWS_SQS_URL