apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: "#{namespace}#"
type: Opaque
stringData:
  MASTER_KEY: "admin-secreto-123"
  DATABASE_URL: "postgres://#{db_user}#:#{db_pass}#@#{rds_endpoint}#/auth_db?sslmode=require"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: "#{namespace}#"
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001