apiVersion: v1
kind: Namespace
metadata:
  name: "#{namespace}#"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-config
  namespace: "#{namespace}#"
data:
  AWS_REGION: "#{location}#"
  AUTH_SERVICE_URL: "http://auth-service.#{namespace}#.svc.cluster.local:8001"
  FLAG_SERVICE_URL: "http://flag-service.#{namespace}#.svc.cluster.local:8002"
  TARGETING_SERVICE_URL: "http://targeting-service.#{namespace}#.svc.cluster.local:8003"

---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secret
  namespace: "#{namespace}#"
type: Opaque
stringData:
  AWS_SQS_URL: "#{aws_sqs_url}#"
  REDIS_URL: "redis://#{aws_cache_endpoint}#"
  SERVICE_API_KEY: "SUA_CHAVE_DE_SERVICO"