apiVersion: v1
kind: Namespace
metadata:
  name: "#{namespace}#"

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: "#{namespace}#"
type: Opaque
stringData:
  MASTER_KEY: "admin-secreto-123"
  DATABASE_URL: "postgres://#{db_user}#:#{db_pass}#@#{rds_auth}#/auth_db"