apiVersion: v1
kind: Namespace
metadata:
  name: "#{namespace}#"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-config
  namespace: "#{namespace}#"
data:
  AUTH_SERVICE_URL: "http://auth-service.#{namespace}#.svc.cluster.local:8001"

---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-secret
  namespace: "#{namespace}#"
type: Opaque
stringData:
  DATABASE_URL: "postgres://#{db_user}#:#{db_pass}#@#{rds_targeting}#/targeting_db"