apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
  namespace: "#{namespace}#"
data:
  AWS_REGION: "us-east-1"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"

---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
  namespace: "#{namespace}#"
type: Opaque
stringData:
  AWS_SQS_URL: "#{aws_sqs_url}#"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-sa
  namespace: "#{namespace}#"
  annotations:
    eks.amazonaws.com/role-arn: "#{aws_evaluation_role_arn}#"
    eks.amazonaws.com/role-arn: "#{aws_analytics_role_arn}#"

---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: "#{namespace}#"
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: analytics-scaledobject
  namespace: "#{namespace}#"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-deployment
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 15
  cooldownPeriod:  60
  triggers:
    - type: aws-sqs-queue
      metadata:
        identityOwner: "operator"
        awsRegion: "us-east-1"
        queueURL: "#{aws_sqs_url}#"
        queueLength: "10"