name: FIAP - MODULO 03 - APP - AUTH SERVICE

on:
  push:
    branches:
      - main
    paths:
      - 'auth-service/**'
  workflow_dispatch:

env:
  SERVICE_NAME: 'auth-service'
  ECR_REPOSITORY_NAME: 'ecr-auth-service-01'
  GO_VERSION: '1.25'

jobs:
  # sca:
  #   name: SCA - TRIVY - FILE SYSTEM SCAN
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Trivy - Vulnerability Scanner
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         scan-type: 'fs'
  #         scan-ref: '${{ github.workspace }}/${{ env.SERVICE_NAME }}'
  #         format: 'table'
  #         exit-code: '0'
  #         severity: 'CRITICAL'
  #         scanners: 'vuln'
  #         trivyignores: '${{ github.workspace }}/${{ env.SERVICE_NAME }}/.trivyignore'

  # sast:
  #   name: SAST - SONARCLOUD - CODE ANALYSIS
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: SonarCloud - Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #       with:
  #         projectBaseDir: ${{ env.SERVICE_NAME }}
  #         args: >
  #           -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
  #           -Dsonar.projectName=${{ github.event.repository.name }}/${{ env.SERVICE_NAME }}
  #           -Dsonar.projectKey=${{ github.event.repository.name }}_${{ env.SERVICE_NAME }}
  #           -Dsonar.go.version=${{ env.GO_VERSION }}
  #           -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.spec.ts,**/*.test.ts,**/*.test.js,**/*.spec.js,**/*.d.ts,**/*.json,**/*.yml,**/*.yaml,**/*.md

  # build-and-test:
  #   name: BUILD, LINT AND UNIT TESTS - SERVICE - AUTH
  #   needs: [sca, sast]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Go - Setup
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: ${{ env.GO_VERSION }}
  #         cache-dependency-path: '${{ env.SERVICE_NAME }}/go.sum'

  #     - name: Go - Install Dependencies
  #       working-directory: ${{ env.SERVICE_NAME }}
  #       run: go mod download

  #     - name: Linter - golangci-lint
  #       working-directory: ${{ env.SERVICE_NAME }}
  #       run: |
  #         go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  #         $(go env GOPATH)/bin/golangci-lint run

  #     - name: Go - Run - Unit Tests
  #       working-directory: ${{ env.SERVICE_NAME }}
  #       run: go test -v ./...

  #     - name: Go - Run - Build
  #       working-directory: ${{ env.SERVICE_NAME }}
  #       run: go build -v -o main .

  docker-build:
    name: DOCKER BUILD - SERVICE - AUTH
    # needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: AWS Credentials - Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: ECR - Connect
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: ECR - Build and Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: 'v1.0.${{ github.sha }}'
        run: |
          cd ${{ env.SERVICE_NAME }}

          echo "##[section]Building the Docker Image..."
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY_NAME }}:$IMAGE_TAG -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY_NAME }}:latest .

          echo "##[section]Pushing Image to ECR..."
          docker push -a $ECR_REGISTRY/${{ env.ECR_REPOSITORY_NAME }}

      - name: Trivy - Container Scan
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: 'v1.0.${{ github.sha }}'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_NAME }}:${{ env.IMAGE_TAG }}'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL'
          scanners: 'vuln'
          trivyignores: '${{ github.workspace }}/${{ env.SERVICE_NAME }}/.trivyignore'

  deploy:
    name: DEPLOY - SERVICE - AUTH
    needs: docker-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      EKS_CLUSTER_NAME: 'eks-cluster-01'
      EKS_NAMESPACE: 'eks-namespace'
      AWS_RDS_NAME: 'rds-auth-db-01'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: AWS Credentials - Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: EKS Cluster - Setup
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: EKS Cluster - Connect
        run: |
          echo "============= EKS Cluster - Connect =============="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Connecting to the EKS Cluster..."
          aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

      - name: ECR - Connect
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: EKS Cluster - Create Dependencies
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: 'v1.0.${{ github.sha }}'
        run: |
          echo "======= EKS Cluster - Create Dependencies ========"
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Getting RDS Endpoint..."
          RDS_ENDPOINT=$(aws rds describe-db-instances \
            --db-instance-identifier ${{ env.AWS_RDS_NAME }} \
            --query "DBInstances[0].Endpoint.Address" \
            --output text)
          echo "##[section]Endpoint found: $RDS_ENDPOINT"

          echo "##[section]Applying Manifests..."
          cd ${{ env.SERVICE_NAME }}
          sed -i "s|postgres://#{db_user}#:#{db_pass}#@#{rds_endpoint}#|postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@$RDS_ENDPOINT|g" k8s/manifests/manifests.yml
          kubectl apply -f k8s/manifests/manifests.yml

      - name: GitOps - Tag Update
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: 'v1.0.${{ github.sha }}'
        run: |
          cd ${{ env.SERVICE_NAME }}

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          sed -i "s|image: .*/${{ env.ECR_REPOSITORY_NAME }}:.*|image: $ECR_REGISTRY/${{ env.ECR_REPOSITORY_NAME }}:$IMAGE_TAG|g" k8s/deployment/deployment.yml
          
          git add k8s/deployment/deployment.yml
          git commit -m "chore(gitops): atualiza imagem do ${{ env.SERVICE_NAME }} para a tag $IMAGE_TAG [skip ci]"
          git push origin HEAD