name: FIAP - MODULO 03 - APP - EVALUATION SERVICE

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'evaluation-service/**'
  workflow_dispatch:

env:
  SERVICE_NAME: 'evaluation-service'
  ECR_REPOSITORY_NAME: 'ecr-evaluation-service-01'
  GO_VERSION: '1.25'

jobs:
  sca:
    name: SCA - TRIVY - FILE SYSTEM SCAN
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Trivy - Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '${{ github.workspace }}/${{ env.SERVICE_NAME }}'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL'
          scanners: 'vuln'
          trivyignores: '${{ github.workspace }}/${{ env.SERVICE_NAME }}/.trivyignore'

  sast:
    name: SAST - SONARCLOUD - CODE ANALYSIS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud - Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ env.SERVICE_NAME }}
          args: >
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
            -Dsonar.projectName=${{ github.event.repository.name }}/${{ env.SERVICE_NAME }}
            -Dsonar.projectKey=${{ github.event.repository.name }}
            -Dsonar.go.version=${{ env.GO_VERSION }}
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.spec.ts,**/*.test.ts,**/*.test.js,**/*.spec.js,**/*.d.ts,**/*.json,**/*.yml,**/*.yaml,**/*.md

  build-and-test:
    name: BUILD, LINT AND UNIT TESTS - SERVICE - EVALUATION
    needs: [sca, sast]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Go - Setup
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: '${{ env.SERVICE_NAME }}/go.sum'

      - name: Go - Install Dependencies
        working-directory: ${{ env.SERVICE_NAME }}
        run: go mod download

      - name: Linter - golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ${{ env.SERVICE_NAME }}

      - name: Go - Run - Unit Tests
        working-directory: ${{ env.SERVICE_NAME }}
        run: go test -v ./...

      - name: Go - Run - Build
        working-directory: ${{ env.SERVICE_NAME }}
        run: go build -v -o main .

  docker-build:
    name: DOCKER BUILD - SERVICE - EVALUATION
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: AWS Credentials - Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: ECR - Connect
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: ECR - Build and Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: 'v1.0.${{ github.sha }}'
        run: |
          cd ${{ env.SERVICE_NAME }}

          echo "##[section]Building the Docker Image..."
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY_NAME }}:$IMAGE_TAG -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY_NAME }}:latest .

          echo "##[section]Pushing Image to ECR..."
          docker push -a $ECR_REGISTRY/${{ env.ECR_REPOSITORY_NAME }}

      - name: Trivy - Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 
          image-ref: '${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_NAME }}:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL'
          scanners: 'vuln'
          trivyignores: '${{ github.workspace }}/${{ env.SERVICE_NAME }}/.trivyignore'